name: GitHub Actions
run-name: build luckfox pro nax image including wifi sdcard driver
on: [push]
jobs:
  build:
    name: build sdk
    runs-on: ubuntu-latest
    container:
      image: luckfoxtech/luckfox_pico:1.0
      volumes:
        - /home/ubuntu/luckfox-pico:/home     
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      
      - run: |
          ./config_restore.sh
          printf '4\n1\n0\n' | ./build.sh conf
          ./build.sh
          tar -czvf image.tar.gz output/image
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar.gz
          
