name: GitHub Actions Demo
run-name: build luckfox max image and toolchain with new uclibc
on: [push]
jobs:
  build:
    name: build sdk
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y git ssh make gcc gcc-multilib g++-multilib module-assistant expect g++ gawk texinfo libssl-dev bison flex fakeroot cmake unzip gperf autoconf device-tree-compiler libncurses5-dev pkg-config bc python-is-python3 passwd openssl openssh-server openssh-client vim file cpio rsync
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          ln -s project/cfg/BoardConfig_IPC/BoardConfig-SPI_NAND-Buildroot-RV1106_Luckfox_Pico_Pro_Max-IPC.mk .BoardConfig.mk
          export PATH=$PATH:$PWD/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin
          make -C sysdrv buildroot_create
          cp myconfig/buildroot_defconfig sysdrv/source/buildroot/buildroot-2023.02.6/configs/luckfox_pico_defconfig
          ./build.sh         
          tar -czvf host.tar.gz sysdrv/source/buildroot/buildroot-2023.02.6/output/host
          tar -czvf image.tar.gz output/image
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildroot sdk
          path: host.tar.gz
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar.gz
          
