name: GitHub Actions
run-name: build luckfox mini image including wifi sdcard driver
on: [push]
jobs:
  build:
    name: build sdk
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y git ssh make gcc gcc-multilib g++-multilib module-assistant expect g++ gawk texinfo libssl-dev bison flex fakeroot cmake unzip gperf autoconf device-tree-compiler libncurses5-dev pkg-config bc python-is-python3 passwd openssl openssh-server openssh-client vim file cpio rsync curl
      - name: Check out repository code
        uses: actions/checkout@v4      
      - run: |
          echo "export PATH=$PATH:$PWD/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf" >> $GITHUB_ENV
          ./build.sh
          tar -czvf host.tar.gz sysdrv/source/buildroot/buildroot-2023.02.6/output/host
          tar -czvf image.tar.gz output/image
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildroot sdk
          path: host.tar.gz
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar.gz
          
